# Generated by Django 2.1.2 on 2018-10-20 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_auto_20181020_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sponsor_components',
        ),
        migrations.DeleteModel(
            name='SponsorComponent',
        ),
    ]
